language: cpp
compiler:
  - clang
notifications:
  email: leah.a.hanson@gmail.com
env:
  matrix: 
    - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init();Pkg.add("FactCheck");Pkg.checkout("FactCheck")'
  - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("TypeCheck"))`); Pkg.pin("TypeCheck"); Pkg.resolve()'
  - julia -e 'using TypeCheck; @assert isdefined(:TypeCheck); @assert typeof(TypeCheck) === Module'
  - julia test/test.jl
